const catalog = [
    {
        id: 0,
        title: 'Пиратский бленд',
        image: 'img/item-image/001.jpg',
        region: 'Эфиопия, Колумбия',
        description: 'Легендарная и на 100% органическая смесь эспрессо для настоящих разбойников',
        kislotnost: 70,
        gorech: 35,
        plotnost: 15,
        price_low: 685,
        price_big: 2450,
    },
    {
        id: 1,
        title: 'Бла-бла-бла',
        image: 'img/item-image/001.jpg',
        region: 'Гватемалла',
        description: 'Просто очень вкусный кофе',
        kislotnost: 25,
        gorech: 50,
        plotnost: 75,
        price_low: 560,
        price_big: 2120,
    },
    {
        id: 3,
        title: 'Хаха получилось',
        image: 'img/item-image/001.jpg',
        region: 'Индонезия',
        description: 'Описание будет позже',
        kislotnost: 90,
        gorech: 20,
        plotnost: 35,
        price_low: 710,
        price_big: 2200,
    }
]